In [1]:
v = [3, 2, 4, 1]

4-element Array{Int64,1}:
 3
 2
 4
 1

In [2]:
sort(v)

4-element Array{Int64,1}:
 1
 2
 3
 4

In [3]:
sortperm(v)

4-element Array{Int64,1}:
 4
 2
 1
 3

In [4]:
d = Dict(1=>3, 2=>4, 3=>5, 4=>-1)

Dict{Int64,Int64} with 4 entries:
  4 => -1
  2 => 4
  3 => 5
  1 => 3

In [5]:
keys(d)

Base.KeySet for a Dict{Int64,Int64} with 4 entries. Keys:
  4
  2
  3
  1

In [6]:
values(d)

Base.ValueIterator for a Dict{Int64,Int64} with 4 entries. Values:
  -1
  4
  5
  3

In [7]:
collect(keys(d))

4-element Array{Int64,1}:
 4
 2
 3
 1

In [9]:
p = sortperm(collect(keys(d)))

4-element Array{Int64,1}:
 4
 2
 3
 1

In [10]:
vs = collect(values(d))

4-element Array{Int64,1}:
 -1
  4
  5
  3

In [11]:
vs[p]

4-element Array{Int64,1}:
  3
  4
  5
 -1

In [12]:
d


Dict{Int64,Int64} with 4 entries:
  4 => -1
  2 => 4
  3 => 5
  1 => 3

In [13]:
Iterators.product(1:3, 1:3)

Base.Iterators.ProductIterator{Tuple{UnitRange{Int64},UnitRange{Int64}}}((1:3, 1:3))

In [14]:
collect(Iterators.product(1:3, 1:3))

3×3 Array{Tuple{Int64,Int64},2}:
 (1, 1)  (1, 2)  (1, 3)
 (2, 1)  (2, 2)  (2, 3)
 (3, 1)  (3, 2)  (3, 3)

In [15]:
collect(Iterators.product(1:6, 1:6, 1:6))

6×6×6 Array{Tuple{Int64,Int64,Int64},3}:
[:, :, 1] =
 (1, 1, 1)  (1, 2, 1)  (1, 3, 1)  (1, 4, 1)  (1, 5, 1)  (1, 6, 1)
 (2, 1, 1)  (2, 2, 1)  (2, 3, 1)  (2, 4, 1)  (2, 5, 1)  (2, 6, 1)
 (3, 1, 1)  (3, 2, 1)  (3, 3, 1)  (3, 4, 1)  (3, 5, 1)  (3, 6, 1)
 (4, 1, 1)  (4, 2, 1)  (4, 3, 1)  (4, 4, 1)  (4, 5, 1)  (4, 6, 1)
 (5, 1, 1)  (5, 2, 1)  (5, 3, 1)  (5, 4, 1)  (5, 5, 1)  (5, 6, 1)
 (6, 1, 1)  (6, 2, 1)  (6, 3, 1)  (6, 4, 1)  (6, 5, 1)  (6, 6, 1)

[:, :, 2] =
 (1, 1, 2)  (1, 2, 2)  (1, 3, 2)  (1, 4, 2)  (1, 5, 2)  (1, 6, 2)
 (2, 1, 2)  (2, 2, 2)  (2, 3, 2)  (2, 4, 2)  (2, 5, 2)  (2, 6, 2)
 (3, 1, 2)  (3, 2, 2)  (3, 3, 2)  (3, 4, 2)  (3, 5, 2)  (3, 6, 2)
 (4, 1, 2)  (4, 2, 2)  (4, 3, 2)  (4, 4, 2)  (4, 5, 2)  (4, 6, 2)
 (5, 1, 2)  (5, 2, 2)  (5, 3, 2)  (5, 4, 2)  (5, 5, 2)  (5, 6, 2)
 (6, 1, 2)  (6, 2, 2)  (6, 3, 2)  (6, 4, 2)  (6, 5, 2)  (6, 6, 2)

[:, :, 3] =
 (1, 1, 3)  (1, 2, 3)  (1, 3, 3)  (1, 4, 3)  (1, 5, 3)  (1, 6, 3)
 (2, 1, 3)  (2, 2, 3)  (2, 3, 3)  (2, 4, 3)  (2, 5, 3)  (2, 6, 

In [17]:
vec(sum.(Iterators.product(1:6, 1:6, 1:6)))

216-element Array{Int64,1}:
  3
  4
  5
  6
  7
  8
  4
  5
  6
  7
  8
  9
  5
  ⋮
 12
 13
 14
 15
 16
 17
 13
 14
 15
 16
 17
 18

In [18]:
vec(sum.(Iterators.product(Iterators.repeated(1:6, 3))))

3-element Array{UnitRange{Int64},1}:
 1:6
 1:6
 1:6

In [20]:
vec(sum.(Iterators.product(Iterators.repeated(1:6, 3)...)))

216-element Array{Int64,1}:
  3
  4
  5
  6
  7
  8
  4
  5
  6
  7
  8
  9
  5
  ⋮
 12
 13
 14
 15
 16
 17
 13
 14
 15
 16
 17
 18

In [21]:
vec(sum.(Iterators.product(Iterators.repeated(1:6, 5)...)))

7776-element Array{Int64,1}:
  5
  6
  7
  8
  9
 10
  6
  7
  8
  9
 10
 11
  7
  ⋮
 24
 25
 26
 27
 28
 29
 25
 26
 27
 28
 29
 30

In [22]:
v = [ ]

0-element Array{Any,1}

In [23]:
push!(v, "hello")

1-element Array{Any,1}:
 "hello"

In [24]:
push!(v, -3.1)

2-element Array{Any,1}:
   "hello"
 -3.1     

In [25]:
v = Int[]

0-element Array{Int64,1}

In [26]:
push!(v, 3.0)

1-element Array{Int64,1}:
 3

In [27]:
push!(v, 3.1)

InexactError: InexactError: Int64(3.1)

In [28]:
v = Float64[]

0-element Array{Float64,1}

In [29]:
push!(v, "hello")

MethodError: MethodError: Cannot `convert` an object of type String to an object of type Float64
Closest candidates are:
  convert(::Type{T}, !Matched::T) where T<:Number at number.jl:6
  convert(::Type{T}, !Matched::Number) where T<:Number at number.jl:7
  convert(::Type{T}, !Matched::Base.TwicePrecision) where T<:Number at twiceprecision.jl:250
  ...

In [30]:
11 ÷ 2

5

In [31]:
div(11, 2)

5

In [39]:
L = 100 
T = 10
P0 = zeros(L) # P\_0<TAB> 
P0[L ÷ 2] = 1
P = copy(P0) # time t 
next_P = copy(P0) # time t+1 Ps = [copy(P0)]

Ps = [copy(P0)]

1-element Array{Array{Float64,1},1}:
 [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0  …  0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]

In [40]:
T = 100
for t in 1:T
    
    for i in 2:L-1   ## bulk -- not boundary
        next_P[i] = 0.5 * (P[i-1] + P[i+1]) 
    end
    
    push!(Ps, copy(next_P))
    global P, next_P = next_P, P
end

# reuse T

In [41]:
Ps

101-element Array{Array{Float64,1},1}:
 [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0  …  0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]                                                                                                                                                               
 [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0  …  0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]                                                                                                                                                               
 [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0  …  0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]                                                                                                                                                               
 [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0  …  0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]                                                                 

In [42]:
using Plots
using Interact

In [44]:
@manipulate for t in 1:T
    plot(Ps[t], m=:o)
    ylims!(0, 0.25)
end

Node{WebIO.DOM}(WebIO.DOM(:html, :div), Any[Node{WebIO.DOM}(WebIO.DOM(:html, :div), Any[Scope(Node{WebIO.DOM}(WebIO.DOM(:html, :div), Any[Node{WebIO.DOM}(WebIO.DOM(:html, :div), Any[Node{WebIO.DOM}(WebIO.DOM(:html, :label), Any["t"], Dict{Symbol,Any}(:className => "interact ",:style => Dict{Any,Any}(:padding => "5px 10px 0px 10px")))], Dict{Symbol,Any}(:className => "interact-flex-row-left")), Node{WebIO.DOM}(WebIO.DOM(:html, :div), Any[Node{WebIO.DOM}(WebIO.DOM(:html, :input), Any[], Dict{Symbol,Any}(:max => 100,:min => 1,:attributes => Dict{Any,Any}(:type => "range",Symbol("data-bind") => "numericValue: index, valueUpdate: 'input', event: {change: function (){this.changes(this.changes()+1)}}","orient" => "horizontal"),:step => 1,:className => "slider slider is-fullwidth",:style => Dict{Any,Any}()))], Dict{Symbol,Any}(:className => "interact-flex-row-center")), Node{WebIO.DOM}(WebIO.DOM(:html, :div), Any[Node{WebIO.DOM}(WebIO.DOM(:html, :p), Any[], Dict{Symbol,Any}(:attributes => Dict("data-bind" => "text: formatted_val")))], Dict{Symbol,Any}(:className => "interact-flex-row-right"))], Dict{Symbol,Any}(:className => "interact-flex-row interact-widget")), Dict{String,Tuple{Observables.AbstractObservable,Union{Nothing, Bool}}}("changes" => (Observable{Int64} with 1 listeners. Value:
0, nothing),"index" => (Observable{Int64} with 2 listeners. Value:
50, nothing)), Set(String[]), nothing, Asset[Asset("js", "knockout", "/Users/dpsanders/.julia/packages/Knockout/1sDlc/src/../assets/knockout.js"), Asset("js", "knockout_punches", "/Users/dpsanders/.julia/packages/Knockout/1sDlc/src/../assets/knockout_punches.js"), Asset("js", nothing, "/Users/dpsanders/.julia/packages/InteractBase/9mFwe/src/../assets/all.js"), Asset("css", nothing, "/Users/dpsanders/.julia/packages/InteractBase/9mFwe/src/../assets/style.css"), Asset("css", nothing, "/Users/dpsanders/.julia/packages/Interact/SbgIk/src/../assets/bulma_confined.min.css")], Dict{Any,Any}("changes" => Any[WebIO.JSString("(function (val){return (val!=this.model[\"changes\"]()) ? (this.valueFromJulia[\"changes\"]=true, this.model[\"changes\"](val)) : undefined})")],"index" => Any[WebIO.JSString("(function (val){return (val!=this.model[\"index\"]()) ? (this.valueFromJulia[\"index\"]=true, this.model[\"index\"](val)) : undefined})")]), WebIO.ConnectionPool(Channel{Any}(sz_max:32,sz_curr:0), Set(AbstractConnection[]), Base.GenericCondition{Base.AlwaysLockedST}(Base.InvasiveLinkedList{Task}(Task (runnable) @0x000000011dc9ef50, Task (runnable) @0x000000011dc9ef50), Base.AlwaysLockedST(1))), WebIO.JSString[WebIO.JSString("function () {\n    var handler = (function (ko, koPunches) {\n    ko.punches.enableAll();\n    ko.bindingHandlers.numericValue = {\n        init: function(element, valueAccessor, allBindings, data, context) {\n            var stringified = ko.observable(ko.unwrap(valueAccessor()));\n            stringified.subscribe(function(value) {\n                var val = parseFloat(value);\n                if (!isNaN(val)) {\n                    valueAccessor()(val);\n                }\n            });\n            valueAccessor().subscribe(function(value) {\n                var str = JSON.stringify(value);\n                if ((str == \"0\") && ([\"-0\", \"-0.\"].indexOf(stringified()) >= 0))\n                     return;\n                 if ([\"null\", \"\"].indexOf(str) >= 0)\n                     return;\n                stringified(str);\n            });\n            ko.applyBindingsToNode(\n                element,\n                {\n                    value: stringified,\n                    valueUpdate: allBindings.get('valueUpdate'),\n                },\n                context,\n            );\n        }\n    };\n    var json_data = {\"formatted_vals\":[\"1\",\"2\",\"3\",\"4\",\"5\",\"6\",\"7\",\"8\",\"9\",\"10\",\"11\",\"12\",\"13\",\"14\",\"15\",\"16\",\"17\",\"18\",\"19\",\"20\",\"21\",\"22\",\"23\",\"24\",\"25\",\"26\",\"27\",\"28\",\"29\",\"30\",\"31\",\"32\",\"33\",\"34\

In [45]:
sum(Ps[1])

1.0

In [46]:
sum.(Ps)

101-element Array{Float64,1}:
 1.0               
 1.0               
 1.0               
 1.0               
 1.0               
 1.0               
 1.0               
 1.0               
 1.0               
 1.0               
 1.0               
 1.0               
 1.0               
 ⋮                 
 0.9999998367894536
 0.9999998139106124
 0.999999765865046 
 0.9999997344469193
 0.999999670068321 
 0.9999996276419488
 0.9999995426785272
 0.9999994862658553
 0.9999993756970189
 0.999999301750679 
 0.9999991597145492
 0.9999990640575639